name: training_notebooks
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - xarray
  - netcdf4
  - cartopy
  - jupyterlab
  - myst-parser
  - nbconvert
  - jupyter
  - cdsapi
  - black-jupyter
  - nbqa
